export const SEARCH_QUERY_SUCCEEDED = 'SEARCH_QUERY_SUCCEEDED';
export const SEARCH_QUERY_FAILED = 'SEARCH_QUERY_FAILED';
export const SEARCH_QUERY = 'SEARCH_QUERY';
export const PLAY_TRACK = 'PLAY_TRACK';
export const ADD_TRACK_QUEUE = 'ADD_TRACK_QUEUE';
export const PLAY_TRACK_QUEUE = 'PLAY_TRACK_QUEUE';
